---
# Title: role-xrdp-server
#
# Author: Bitfinity-NL
# File: tasks/xrdp-pulse-audio.yml
#
# Description:
#   An open-source Remote Desktop Protocol server.
#
# Sources:
#   https://c-nergy.be/blog/?p=13655
#

- name: "Enable source repositories"
  replace:
    path: /etc/apt/sources.list
    regexp: '# deb-src'
    replace: 'deb-src'

- name: "Update repositories cache"
  apt:
    update_cache: yes

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - git 
    - libpulse-dev 
    - autoconf
    - m4
    - intltool
    - build-essential
    - dpkg-dev

- name: "Ensure the package build dependencies are installed"
  apt:
    pkg: pulseaudio
    state: build-dep

- name: "Download pulseaudio source in /tmp directory"
  command: apt source pulseaudio
  args:
    chdir: /tmp

- name: "Discover Directory"
  shell: "pulseaudio --version | awk '{print $2}'"
  register: pulseversion

- name: "Display pulseaudio version"
  debug:
    var: pulseversion.stdout
   
- name: "Compile"
  command: ./configure
  args: 
    chdir: /tmp/pulseaudio-{{ pulseversion.stdout }}

- name: "Clone repository from git"
  git:
    repo: https://github.com/neutrinolabs/pulseaudio-module-xrdp.git
    dest: /tmp/pulseaudio-{{ pulseversion.stdout }}/pulseaudio-module-xrdp/    

- name: "Create xrdp sound modules"
  shell:
    cmd: "{{ item }}"
    chdir: /tmp/pulseaudio-{{ pulseversion.stdout }}/pulseaudio-module-xrdp/
  with_items:
    - ./bootstrap.sh
    - ./configure PULSE_DIR="/home/ansible/pulseaudio-{{ pulseversion.stdout }}"
    - make

- name: "Transfer files to the correct location"
  shell:
    cmd: install -t "/var/lib/xrdp-pulseaudio-installer" -D -m 644 *.so
    chdir: /tmp/pulseaudio-{{ pulseversion.stdout }}/pulseaudio-module-xrdp/src/.libs/

- name: "Disable  source repositories"
  replace:
    path: /etc/apt/sources.list
    regexp: 'deb-src'
    replace: '# deb-src'

- name: "Update repositories cache"
  apt:
    update_cache: yes
